### PR TITLE
Adding the local of event on map.

### PR DESCRIPTION
**Pull request by morvanabonin**

### CODE REVIEW

**Comment by olizilla** [comment]
Welcome Porto Alegre!
It looks like you missed a comma after what was the last entry in the the list, can you add it please, otherwise we'll get an error trying to render the map. Thanks!

**Comment by morvanabonin** [comment]
Sorry about it! I fixed now!

**Comment by olizilla** [comment]
Great! Thanks. Have a super fun nodebots day! :tada:

**Comment by morvanabonin** [comment]
Yeap! \o/ 
Thanks @olizilla!

**Pull request merged**
