### PR TITLE
Nice up the nodebots.io for International NodeBots Day 2014

### PR DESCRIPTION
**Pull request by olizilla**
Dear NodeBots Team, I've been tinkering with a clean up of the nodebots.io site for a while now, and with NodeBots day around the corner, I think it's finally ready... hope you like it!

screen shot 2014-07-02 at 23 50 11

The components in the equation were shamelessly ripped from the robots conf site, but I figured as it's @voodootikigod all the way down, it wouldn't be a problem. 

I've tweaked the copy and added a map of the locations that have added themselves to the nodebots day list
screen shot 2014-07-03 at 00 00 48

### CODE REVIEW

**Comment by voodootikigod** [comment]
THIS IS FANTASTIC ILOVE IT!!!

**Comment by olizilla** [comment]
:heart_eyes_cat: Updated, with a handful of fix-up sprinkles added for good measure...

**Comment by cwaring** [comment]
Hot stuff mr @olizilla, you have full credit to use my panography. Looking forward to the next one!

**Comment by olizilla** [comment]
Super thanks mr @cwaring... It would be remiss of me not to add you as a photo credit on the site. Do you perchance have a higher quality version? I pulled the current one out from the meetup.com

**Comment by cwaring** [comment]
I have this one...
793641_10152111359067355_679389045_o 1
If you need giga pixels I'll excavate the archives soon.

**Comment by SaraJo** [comment]
looks awesome, super stoked.

Sara J Chipps
862.201.3065
CTO Flatiron School http://flatironschool.com, Flatiron Labs
http://flatironlabs.com

_Blog_
http://SaraJChipps.com http://sarajchipps.com/

_Projects_
http://GirlDevelopIt.com http://girldevelopit.com/
http://Levo.com http://levoleague.com/
http://ElizabethandClarke.com http://elizabethandclarke.com/

---

No trees were killed in sending this message but a large number of
electrons were terribly inconvenienced.

**Comment by garrows** [comment]
@olizilla I love your design. I had originally got permission from @voodootikigod to use his old design (as there was a copywrite on it) for the nodebots Australia website (http://nodebotsau.io) and when I saw it was updated I assumed it was his so I copied the new one. I hope you dont mind us using it?

**Comment by olizilla** [comment]
@garrows glad you like it! Feel free to re-use it. I've upped the header image quality and added a photo attribution so you might wanna grab that too.

**Comment by olizilla** [comment]
@reconbot :heart: ...finally, a reason to css animate.

If anyone wants to use blinky the nodebot in a thing, he hangs out here:
http://jsbin.com/iKaGel/17/edit?css,output

**Pull request merged**
